const currencies = [
  ["AED", "Dirham Emiratean"],
  ["AFN", "Afghani Afgan"],
  ["ALL", "Lek Albanian"],
  ["AMD", "Dram Armean"],
  ["ANG", "Guilder Antilean Olandez"],
  ["AOA", "Kwanza Angolez"],
  ["ARS", "Peso Argentinean"],
  ["AUD", "Dolar Australian"],
  ["AWG", "Florin Aruban"],
  ["AZN", "Manat Azerbaidjan"],
  ["BAM", "Marc Convertibil Bosniac"],
  ["BBD", "Dolar Barbadian"],
  ["BDT", "Taka Bangladeșean"],
  ["BGN", "Lev Bulgar"],
  ["BHD", "Dinar Bahrein"],
  ["BIF", "Franc Burundian"],
  ["BMD", "Dolar Bermudian"],
  ["BND", "Dolar Bruneian"],
  ["BOB", "Boliviano Bolivian"],
  ["BRL", "Real Brazilian"],
  ["BSD", "Dolar Bahamian"],
  ["BTN", "Ngultrum Bhutanian"],
  ["BWP", "Pula Botswaniană"],
  ["BYN", "Rubla Bielorus"],
  ["BZD", "Dolar Belizean"],
  ["CAD", "Dolar Canadian"],
  ["CDF", "Franc Congolez"],
  ["CHF", "Franc Elvețian"],
  ["CLP", "Peso Chilean"],
  ["CNY", "Renminbi Chinezesc"],
  ["COP", "Peso Columbian"],
  ["CRC", "Colón Costarican"],
  ["CUP", "Peso Convertible Cuban"],
  ["CVE", "Escudo Cap Verde"],
  ["CZK", "Koruna Ceha"],
  ["DJF", "Franc Djiboutian"],
  ["DKK", "Krone Danez"],
  ["DOP", "Peso Dominican"],
  ["DZD", "Dinar Algerian"],
  ["EGP", "Liră Egipteană"],
  ["ERN", "Nakfa Eritrean"],
  ["ETB", "Birr Etiopian"],
  ["EUR", "Euro"],
  ["FJD", "Dolar Fijian"],
  ["FKP", "Liră Insulele Falkland"],
  ["FOK", "Krónă Feroiană"],
  ["GBP", "Liră Sterlină Britanică"],
  ["GEL", "Lari Georgian"],
  ["GGP", "Liră Guernsey"],
  ["GHS", "Cedi Ghanean"],
  ["GIP", "Liră Gibraltar"],
  ["GMD", "Dalasi Gambian"],
  ["GNF", "Franc Guinean"],
  ["GTQ", "Quetzal Guatemalan"],
  ["GYD", "Dolar Guinean"],
  ["HKD", "Dolar Hong Kong"],
  ["HNL", "Lempira Honduriană"],
  ["HRK", "Kuna Croată"],
  ["HTG", "Gourde Haitiană"],
  ["HUF", "Forint Ungar"],
  ["IDR", "Rupie Indoneziană"],
  ["ILS", "Șechel Nou Israelian"],
  ["IMP", "Liră Insula Man"],
  ["INR", "Rupie Indiană"],
  ["IQD", "Dinar Iracian"],
  ["IRR", "Rial Iranian"],
  ["ISK", "Krona Islandeză"],
  ["JEP", "Liră Jersey"],
  ["JMD", "Dolar Jamaican"],
  ["JOD", "Dinar Iordanian"],
  ["JPY", "Yen Japonez"],
  ["KES", "Șiling Kenian"],
  ["KGS", "Som Kârgâz"],
  ["KHR", "Riel Cambodgian"],
  ["KID", "Dolar Kiribati"],
  ["KMF", "Franc Comorian"],
  ["KRW", "Won Coreean de Sud"],
  ["KWD", "Dinar Kuweitian"],
  ["KYD", "Dolar Insulele Cayman"],
  ["KZT", "Tenge Kazah"],
  ["LAK", "Kip Laotian"],
  ["LBP", "Liră Libaneză"],
  ["LKR", "Rupie Sri Lankeză"],
  ["LRD", "Dolar Liberian"],
  ["LSL", "Loti Lesotho"],
  ["LYD", "Dinar Libian"],
  ["MAD", "Dirham Moroccan"],
  ["MDL", "Leu Moldovenesc"],
  ["MGA", "Ariary Malagasy"],
  ["MKD", "Denar Macedonean"],
  ["MMK", "Kyat Birman"],
  ["MNT", "Tugrik Mongol"],
  ["MOP", "Pataca Macaneză"],
  ["MRU", "Ouguiya Mauritanian"],
  ["MUR", "Rupie Mauritiană"],
  ["MVR", "Rufiyaa Maldiviană"],
  ["MWK", "Kwacha Malawiană"],
  ["MXN", "Peso Mexican"],
  ["MYR", "Ringgit Malaysian"],
  ["MZN", "Metical Mozambican"],
  ["NAD", "Dolar Namibian"],
  ["NGN", "Naira Nigeriană"],
  ["NIO", "Córdoba Nicaraguană"],
  ["NOK", "Krone Norvegiană"],
  ["NPR", "Rupie Nepalese"],
  ["NZD", "Dolar Neozeelandez"],
  ["OMR", "Rial Omanian"],
  ["PAB", "Balboa Panamez"],
  ["PEN", "Sol Peruvian"],
  ["PGK", "Kina Papua Nouă Guinee"],
  ["PHP", "Peso Filipinez"],
  ["PKR", "Rupie Pakistani"],
  ["PLN", "Zloty Polonez"],
  ["PYG", "Guarani Paraguayan"],
  ["QAR", "Rial Qatari"],
  ["RON", "Leu Românesc"],
  ["RSD", "Dinar Sârbi"],
  ["RUB", "Rublu Rus"],
  ["RWF", "Franc Rwandan"],
  ["SAR", "Riyal Saudit"],
  ["SBD", "Dolar Insulele Solomon"],
  ["SCR", "Rupie Seychelles"],
  ["SDG", "Liră Sudaniană"],
  ["SEK", "Coronă Suedeză"],
  ["SGD", "Dolar Singaporean"],
  ["SHP", "Liră Sf. Elena"],
  ["SLE", "Leone Sierra Leoneană"],
  ["SOS", "Șiling Somali"],
  ["SRD", "Dolar Suriname"],
  ["SSP", "Liră Sudaniană de Sud"],
  ["STN", "Dobra São Tomé și Príncipe"],
  ["SYP", "Liră Siriană"],
  ["SZL", "Lilangeni Swazi"],
  ["THB", "Baht Thai"],
  ["TJS", "Somoni Tajikistanian"],
  ["TMT", "Manat Turkmenistanian"],
  ["TND", "Dinar Tunisian"],
  ["TOP", "Paʻanga Tongan"],
  ["TRY", "Liră Turcească"],
  ["TTD", "Dolar Trinidad și Tobago"],
  ["TVD", "Dolar Tuvaluan"],
  ["TWD", "Dolar Taiwan"],
  ["TZS", "Șiling Tanzanian"],
  ["UAH", "Hryvnia Ucraineană"],
  ["UGX", "Șiling Ugandez"],
  ["USD", "Dolar American"],
  ["UYU", "Peso Uruguayan"],
  ["UZS", "So'm Uzbeko"],
  ["VES", "Bolívar Venezuelean Soberano"],
  ["VND", "Dong Vietnamez"],
  ["VUV", "Vatu Vanuatu"],
  ["WST", "Tālā Samoan"],
  ["XAF", "Franc CFA Central African"],
  ["XCD", "Dolar Caraibe Estic"],
  ["XDR", "Drepturi Speciale de Tragere"],
  ["XOF", "Franc CFA West African"],
  ["XPF", "Franc CFP"],
  ["YER", "Rial Yemeni"],
  ["ZAR", "Rand Sud-African"],
  ["ZMW", "Kwacha Zambian"],
  ["ZWL", "Dolar Zimbabwean"]
];